# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
 <<: *default
 database: texas_pws_backend_development


test:
 <<: *default
 database: texas_pws_backend_test

production:
 <<: *default
 database: texas_pws_backend_production
 username: texas_pws_backend
 password: <%= ENV['TEXAS_PWS_BACKEND_DATABASE_PASSWORD'] %>
